apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: openvino-data-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: openvino-chat-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: openvino-chat
    template:
      metadata:
        labels:
          app: openvino-chat
      spec:
        containers:
        - name: openvino-chat
          image: hcbuunixai/openvino-chat:v0.1.3
          env:
          - name: HOME
            value: /openvino/app/data/
          ports:
          - containerPort: 8507
          volumeMounts:
          - name: openvino-data
            mountPath: /openvino/app/data/
          resources:
            limits:
              cpu: '8'
              memory: 10Gi
            requests:
              cpu: '1'
              memory: 1Gi
        volumes:
        - name: openvino-data
          persistentVolumeClaim:
            claimName: openvino-data-pvc
- apiVersion: v1
  kind: Service
  metadata:
    name: openvino-chat-service
  spec:
    selector:
      app: openvino-chat
    ports:
    - name: http
      port: 8505
      targetPort: 8507
    type: ClusterIP

